### PR TITLE
added a forged long-lived cookie to avoid GDPR/CCPA/COPPA ageGate

### PR DESCRIPTION
**Pull request by adud**
tested only for GDPR (France) though

### CODE REVIEW

**Comment by raehik** [comment]
This is nice, thanks for these PRs. Glad this still is still helping folks out.

**Comment by raehik** [comment]
I've just rebased after merging your other PR. Is it all working as you expect?

**Comment by adud** [comment]
I just had to invert the jar add and the request opener, works fine now (at least in France).
Sorry for having messed up the history. I'll think of it next time, before proposing two features around the same lines of the same file.

**Comment by raehik** [comment]
Not a problem, I think your approach is usually best. In similar circumstances I've "ordered" my PRs to have one branching off the other, but merging is a fact of life in Git anyway.

**Pull request merged**
